; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
upload_port = COM4
monitor_port = COM4
build_flags =
    -DFEATURE_LORA=1
    -DFEATURE_OLED=1
    -DFEATURE_COMMS=1
    -DFEATURE_MODBUS=1



lib_deps =
    sandeepmistry/LoRa
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson

[env:esp32dev_minimal]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DFEATURE_LORA=0
    -DFEATURE_OLED=0
    -DFEATURE_COMMS=0
    -DFEATURE_MODBUS=0
lib_deps =
    bblanchon/ArduinoJson
